name = "Drapit Virtual Try-On"
client_id = "b4be0e4c410809e0f2b872950484cae1"
application_url = "https://drapit.netlify.app"
embedded = true

[auth]
redirect_urls = [
  "https://drapit.io/api/auth/callback",
  "https://drapit.io/api/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[access_scopes]
scopes = "write_products,read_themes,write_themes"

[pos]
embedded = false

