name = "Drapit Virtual Try-On"
client_id = "15c8afc4a1e0648dde6da5870549dcb0"
application_url = "https://drapit.io"
embedded = true

[auth]
redirect_urls = [
  "https://drapit.io/api/auth/callback",
  "https://drapit.io/api/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[access_scopes]
scopes = "write_products,read_themes,write_themes"

[pos]
embedded = false

