# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15c8afc4a1e0648dde6da5870549dcb0"
name = "Drapit Virtual Try-On"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
